name: doauth2
version: 0.2.0
author: KH Chan <kwunhok@gmail.com>
description: A Dart OAuth2 library
homepage: http://github.com/chankh/doauth2
environment:
  sdk: '>=0.8.10+6<2.0.0'
dependencies:
  json: '>=0.9.0 < 0.10.0'
  logging: '>=0.9.0 < 0.10.0'
  unittest: '>=0.9.0 < 0.10.0'
